using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArgeKassenbuch.Data.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Sichere Migration: Erstellt Tabellen nur wenn sie noch nicht existieren.
            // Damit funktioniert diese Migration sowohl auf einer komplett neuen DB
            // als auch auf einer bestehenden DB (erstellt mit EnsureCreated).
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""AppEinstellungen"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""AdminPasswort"" text NOT NULL,
                    ""AktiveVeranstaltungId"" integer,
                    ""OrganisationsName"" text NOT NULL,
                    CONSTRAINT ""PK_AppEinstellungen"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Bedienungen"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Vorname"" text NOT NULL,
                    ""Nachname"" text NOT NULL,
                    ""Telefon"" text,
                    ""Aktiv"" boolean NOT NULL,
                    CONSTRAINT ""PK_Bedienungen"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Benutzer"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Benutzername"" text NOT NULL,
                    ""PasswortHash"" text NOT NULL,
                    ""Anzeigename"" text NOT NULL,
                    ""Rolle"" text NOT NULL,
                    ""Aktiv"" boolean NOT NULL,
                    ""ErstelltAm"" timestamp without time zone NOT NULL,
                    ""LetzterLogin"" timestamp without time zone,
                    CONSTRAINT ""PK_Benutzer"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Bons"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""VeranstaltungId"" integer NOT NULL,
                    ""BedienungId"" integer,
                    ""VerkaufsstandId"" integer,
                    ""BonNummer"" integer NOT NULL,
                    ""Gesamtbetrag"" numeric(10,2) NOT NULL,
                    ""ErstelltAm"" timestamp without time zone NOT NULL,
                    ""Storniert"" boolean NOT NULL,
                    ""Bemerkung"" text,
                    CONSTRAINT ""PK_Bons"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""KassenbuchEintraege"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""VeranstaltungId"" integer NOT NULL,
                    ""Typ"" text NOT NULL,
                    ""Betrag"" numeric(10,2) NOT NULL,
                    ""Beschreibung"" text NOT NULL,
                    ""ReferenzId"" integer,
                    ""Zeitpunkt"" timestamp without time zone NOT NULL,
                    ""ErstelltVon"" text,
                    CONSTRAINT ""PK_KassenbuchEintraege"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""SafeBags"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""VeranstaltungId"" integer NOT NULL,
                    ""Nummer"" text NOT NULL,
                    ""Kasseninhalt"" numeric NOT NULL,
                    ""Wechselgeld"" numeric NOT NULL,
                    ""Betrag"" numeric(10,2) NOT NULL,
                    ""VerkaufsstandId"" integer,
                    ""ErstelltVon"" text,
                    ""ErstelltAm"" timestamp without time zone NOT NULL,
                    ""ImTresor"" boolean NOT NULL,
                    ""Bemerkung"" text,
                    CONSTRAINT ""PK_SafeBags"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Schichten"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""VeranstaltungId"" integer NOT NULL,
                    ""PersonName"" text NOT NULL,
                    ""Telefon"" text,
                    ""Von"" timestamp without time zone NOT NULL,
                    ""Bis"" timestamp without time zone NOT NULL,
                    ""Rolle"" text,
                    ""Bemerkung"" text,
                    CONSTRAINT ""PK_Schichten"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""TresorBestaende"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""VeranstaltungId"" integer NOT NULL,
                    ""Stueckelung"" text NOT NULL,
                    ""Wert"" numeric(10,2) NOT NULL,
                    ""Anzahl"" integer NOT NULL,
                    CONSTRAINT ""PK_TresorBestaende"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""TresorBewegungen"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""VeranstaltungId"" integer NOT NULL,
                    ""Typ"" text NOT NULL,
                    ""Betrag"" numeric(10,2) NOT NULL,
                    ""Empfaenger"" text,
                    ""Verwendungszweck"" text,
                    ""Bemerkung"" text,
                    ""Zeitpunkt"" timestamp without time zone NOT NULL,
                    CONSTRAINT ""PK_TresorBewegungen"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Uebergabeprotokolle"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""VeranstaltungId"" integer NOT NULL,
                    ""Zeitpunkt"" timestamp without time zone NOT NULL,
                    ""UebergebenVon"" text NOT NULL,
                    ""UebergebenAn"" text NOT NULL,
                    ""AnzahlSafeBags"" integer NOT NULL,
                    ""WechselgeldHoehe"" numeric(10,2) NOT NULL,
                    ""SchluesselUebergeben"" boolean NOT NULL,
                    ""Bemerkung"" text,
                    ""UnterschriftVon"" text,
                    ""UnterschriftAn"" text,
                    CONSTRAINT ""PK_Uebergabeprotokolle"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Veranstaltungen"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text NOT NULL,
                    ""Typ"" text NOT NULL,
                    ""Datum"" timestamp without time zone NOT NULL,
                    ""DatumBis"" timestamp without time zone,
                    ""Aktiv"" boolean NOT NULL,
                    ""Bemerkung"" text,
                    CONSTRAINT ""PK_Veranstaltungen"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Vereine"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text NOT NULL,
                    ""Kuerzel"" text NOT NULL,
                    ""Aktiv"" boolean NOT NULL,
                    CONSTRAINT ""PK_Vereine"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Verkaufsstaende"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text NOT NULL,
                    ""Beschreibung"" text,
                    ""Aktiv"" boolean NOT NULL,
                    CONSTRAINT ""PK_Verkaufsstaende"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Waren"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text NOT NULL,
                    ""Preis"" numeric(10,2) NOT NULL,
                    ""WarengruppeId"" integer,
                    ""VerkaufsstandId"" integer,
                    ""Aktiv"" boolean NOT NULL,
                    CONSTRAINT ""PK_Waren"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Warengruppen"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text NOT NULL,
                    ""VerkaufsstandId"" integer,
                    ""Aktiv"" boolean NOT NULL,
                    CONSTRAINT ""PK_Warengruppen"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Wechselgelder"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""VeranstaltungId"" integer NOT NULL,
                    ""Aktion"" text NOT NULL,
                    ""Betrag"" numeric(10,2) NOT NULL,
                    ""EmpfaengerName"" text,
                    ""BedienungId"" integer,
                    ""VerkaufsstandId"" integer,
                    ""Zeitpunkt"" timestamp without time zone NOT NULL,
                    ""Bemerkung"" text,
                    CONSTRAINT ""PK_Wechselgelder"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""BonPositionen"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""BonId"" integer NOT NULL,
                    ""WareId"" integer NOT NULL,
                    ""WareName"" text NOT NULL,
                    ""Anzahl"" integer NOT NULL,
                    ""Einzelpreis"" numeric(10,2) NOT NULL,
                    CONSTRAINT ""PK_BonPositionen"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BonPositionen_Bons_BonId"" FOREIGN KEY (""BonId"") REFERENCES ""Bons"" (""Id"") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS ""VeranstaltungVereine"" (
                    ""VeranstaltungId"" integer NOT NULL,
                    ""VereinId"" integer NOT NULL,
                    CONSTRAINT ""PK_VeranstaltungVereine"" PRIMARY KEY (""VeranstaltungId"", ""VereinId""),
                    CONSTRAINT ""FK_VeranstaltungVereine_Veranstaltungen_VeranstaltungId"" FOREIGN KEY (""VeranstaltungId"") REFERENCES ""Veranstaltungen"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_VeranstaltungVereine_Vereine_VereinId"" FOREIGN KEY (""VereinId"") REFERENCES ""Vereine"" (""Id"") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Benutzer_Benutzername"" ON ""Benutzer"" (""Benutzername"");
                CREATE INDEX IF NOT EXISTS ""IX_BonPositionen_BonId"" ON ""BonPositionen"" (""BonId"");
                CREATE INDEX IF NOT EXISTS ""IX_VeranstaltungVereine_VereinId"" ON ""VeranstaltungVereine"" (""VereinId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AppEinstellungen");

            migrationBuilder.DropTable(
                name: "Bedienungen");

            migrationBuilder.DropTable(
                name: "Benutzer");

            migrationBuilder.DropTable(
                name: "BonPositionen");

            migrationBuilder.DropTable(
                name: "KassenbuchEintraege");

            migrationBuilder.DropTable(
                name: "SafeBags");

            migrationBuilder.DropTable(
                name: "Schichten");

            migrationBuilder.DropTable(
                name: "TresorBestaende");

            migrationBuilder.DropTable(
                name: "TresorBewegungen");

            migrationBuilder.DropTable(
                name: "Uebergabeprotokolle");

            migrationBuilder.DropTable(
                name: "VeranstaltungVereine");

            migrationBuilder.DropTable(
                name: "Verkaufsstaende");

            migrationBuilder.DropTable(
                name: "Waren");

            migrationBuilder.DropTable(
                name: "Warengruppen");

            migrationBuilder.DropTable(
                name: "Wechselgelder");

            migrationBuilder.DropTable(
                name: "Bons");

            migrationBuilder.DropTable(
                name: "Veranstaltungen");

            migrationBuilder.DropTable(
                name: "Vereine");
        }
    }
}
