// <auto-generated />
using System;
using ArgeKassenbuch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArgeKassenbuch.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArgeKassenbuch.Models.AppEinstellungen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminPasswort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("AktiveVeranstaltungId")
                        .HasColumnType("integer");

                    b.Property<string>("OrganisationsName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppEinstellungen");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Bedienung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<int?>("BenutzerId")
                        .HasColumnType("integer");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bedienungen");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Anzeigename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Benutzername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LetzterLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswortHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Benutzername")
                        .IsUnique();

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.BenutzerEinladung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BenutzerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GueltigBis")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Verwendet")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("BenutzerEinladungen");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Bon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BedienungId")
                        .HasColumnType("integer");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("text");

                    b.Property<int>("BonNummer")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Gesamtbetrag")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("Storniert")
                        .HasColumnType("boolean");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("integer");

                    b.Property<int?>("VerkaufsstandId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Bons");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.BonPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anzahl")
                        .HasColumnType("integer");

                    b.Property<int>("BonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Einzelpreis")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("WareId")
                        .HasColumnType("integer");

                    b.Property<string>("WareName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BonId");

                    b.ToTable("BonPositionen");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.KassenbuchEintrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ErstelltVon")
                        .HasColumnType("text");

                    b.Property<int?>("ReferenzId")
                        .HasColumnType("integer");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("KassenbuchEintraege");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.SafeBag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bemerkung")
                        .HasColumnType("text");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ErstelltVon")
                        .HasColumnType("text");

                    b.Property<bool>("ImTresor")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Kasseninhalt")
                        .HasColumnType("numeric");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("integer");

                    b.Property<int?>("VerkaufsstandId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Wechselgeld")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SafeBags");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Schicht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bemerkung")
                        .HasColumnType("text");

                    b.Property<DateTime>("Bis")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rolle")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Von")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Schichten");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.TresorBestand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Anzahl")
                        .HasColumnType("integer");

                    b.Property<string>("Stueckelung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Wert")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("TresorBestaende");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.TresorBewegung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bemerkung")
                        .HasColumnType("text");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Empfaenger")
                        .HasColumnType("text");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("integer");

                    b.Property<string>("Verwendungszweck")
                        .HasColumnType("text");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("TresorBewegungen");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Uebergabeprotokoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnzahlSafeBags")
                        .HasColumnType("integer");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("text");

                    b.Property<bool>("SchluesselUebergeben")
                        .HasColumnType("boolean");

                    b.Property<string>("UebergebenAn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UebergebenVon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnterschriftAn")
                        .HasColumnType("text");

                    b.Property<string>("UnterschriftVon")
                        .HasColumnType("text");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("integer");

                    b.Property<decimal>("WechselgeldHoehe")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Uebergabeprotokolle");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Veranstaltung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("text");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DatumBis")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Veranstaltungen");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.VeranstaltungVerein", b =>
                {
                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("integer");

                    b.Property<int>("VereinId")
                        .HasColumnType("integer");

                    b.HasKey("VeranstaltungId", "VereinId");

                    b.HasIndex("VereinId");

                    b.ToTable("VeranstaltungVereine");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Verein", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Kuerzel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vereine");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Verkaufsstand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Verkaufsstaende");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Ware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preis")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("VerkaufsstandId")
                        .HasColumnType("integer");

                    b.Property<int?>("WarengruppeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Waren");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Warengruppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VerkaufsstandId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Warengruppen");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Wechselgeld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aktion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BedienungId")
                        .HasColumnType("integer");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("text");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("EmpfaengerName")
                        .HasColumnType("text");

                    b.Property<int>("VeranstaltungId")
                        .HasColumnType("integer");

                    b.Property<int?>("VerkaufsstandId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Wechselgelder");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.BonPosition", b =>
                {
                    b.HasOne("ArgeKassenbuch.Models.Bon", null)
                        .WithMany("Positionen")
                        .HasForeignKey("BonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.VeranstaltungVerein", b =>
                {
                    b.HasOne("ArgeKassenbuch.Models.Veranstaltung", "Veranstaltung")
                        .WithMany("VeranstaltungVereine")
                        .HasForeignKey("VeranstaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArgeKassenbuch.Models.Verein", "Verein")
                        .WithMany()
                        .HasForeignKey("VereinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veranstaltung");

                    b.Navigation("Verein");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Bon", b =>
                {
                    b.Navigation("Positionen");
                });

            modelBuilder.Entity("ArgeKassenbuch.Models.Veranstaltung", b =>
                {
                    b.Navigation("VeranstaltungVereine");
                });
#pragma warning restore 612, 618
        }
    }
}
